### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by SterlingButters** [drunnells/alexa-mint-skill#2]
In last step of tutorial:
Type "Mint get my bank balance" in the simulator and confirm that no obvious errors appear in the returned JSON.

I get the error in the title. MintAPI works fine. Alexa skill files are stored under: https://<domain.com>/
i.e. I can access alexa.php on the web via https://<domain.com>/alexa.php (a "[]" is displayed) and this is the exact endpoint I have listed in the Service Simulator. Why am I getting this service response? Please Help, I am so close

**Comment by SterlingButters** [comment]
Whoops, Just needed the option saying it's part of a subdomain on a wildcard SSL cert

**Comment by drunnells** [comment]
Glad that you got it working!
